### ISSUE TITLE
Question: overrideing styles from EDS

### ISSUE THREAD

**Issue by FredrikMWold** [equinor/amplify-components#597]
The `Chip` component from EDS does not look optimal in my opionion the text and "action" button are not aligned, and to me it looks messy: 
![image](https://github.com/equinor/amplify-components/assets/25079611/0625adc6-a4c5-4901-9e57-0519c193fc8c)

I can fix the aligment, but to do that i need to override the base styles from EDS. In the `Chip` component you are already adding/overrding some of the style for varients and readonly. Is overriding the base styles of the component something is acceptable in the amplify library?

**Comment by mariush2** [comment]
This is something we do on some components (as you mentioned), but the way we do it is usually to run it by the designers first and then do the change in amplify-components. If you need the fix now I think the best is just to do it locally in your project, we're in the process of restructuring amplify-components atm so things will probably get moved around

**Comment by FredrikMWold** [comment]
Hey. the problem with fixing it locally is that the `Combobox` also uses the Chip component and there is no good way to target the Chips inside the `Combobox` . There is a data attribute for tests that can be used, but that could easly be changes without any breaking changes being reported. Could adding a class or attribute to the `Chip` component that i could target be an idea?

Or is it best to wait for the restructuering?

@mariush2
